export const listings = [
  {
    id: "1",
    image: "/images/hero_image.jpg",
    price: "NGN 1,050,000",
    address: "651 Bay Parkway 102, Dover, ID 83825",
    beds: 2,
    baths: 2,
    size: "1,425 SQ.FT.",
  },
  {
    id: "2",
    image: "/images/hero_image.jpg",
    price: "NGN 8,450,000",
    address: "651 Dover Bay Parkway #902, Dover, ID 83825",
    beds: 2,
    baths: 2,
    size: "1,425 SQ.FT.",
  },
  {
    id: "3",
    image: "/images/hero_image.jpg",
    price: "NGN 100,895,000",
    address: "20 Dover Bay Gardens #92, Hansel, ID 83825",
    beds: 2,
    baths: 2,
    size: "1,506 SQ.FT.",
  },
  {
    id: "4",
    image: "/images/hero_image.jpg",
    price: "NGN 100,895,903",
    address: "20 Dover Bay Gardens #92, Hansel, ID 83825",
    beds: 2,
    baths: 2,
    size: "1,506 SQ.FT.",
  },
  {
    id: "5",
    image: "/images/hero_image.jpg",
    price: "NGN 695,000,000",
    address: "102 S Riverwood Ct, Post Falls, ID 83854",
    beds: 5,
    baths: 3,
    size: "2,664 SQ.FT.",
  },
  {
    id: "7",
    image: "/images/hero_image.jpg",
    price: "NGN 699,335,000",
    address: "102 S Riverwood Ct, Post Falls, ID 83854",
    beds: 5,
    baths: 3,
    size: "2,664 SQ.FT.",
  },
];

export const blogPosts = [
  {
    id: "best-roi-home-improvements",
    image: "/images/hero-image-1.jpg",
    title: "Best ROI Home Improvements for Your Home",
    author: "Cindy Bond",
    date: "June 13, 2024",
    excerpt: "Best ROI Home Improvements for Your Home",
  },
  {
    id: "things-to-do-in-sandpoint",
    image: "/images/hero-image-2.jpg",
    title: "Things to Do in Sandpoint, ID",
    author: "Cindy Bond",
    date: "June 18, 2024",
    excerpt: "Best ROI Home Improvements for Your Home",
  },
  {
    id: "20-condo-upgrade-ideas",
    image: "/images/hero_image.jpg",
    title: "20 Condo Upgrade Ideas",
    author: "Cindy Bond",
    date: "July 10, 2024",
    excerpt: "Best ROI Home Improvements for Your Home",
  },
  {
    id: "everything-you-need-to-know-about-moving-to-sandpoint",
    image: "/images/hero-image-1.jpg",
    title: "Everything You Need to Know About Moving to Sandpoint, ID",
    author: "Cindy Bond",
    date: "April 18, 2024",
    excerpt: "Best ROI Home Improvements for Your Home",
  },
  {
    id: "buying-a-home-in-sandpoint",
    image: "/images/hero_image.jpg",
    title: "Buying a Home in Sandpoint, ID",
    author: "Cindy Bond",
    date: "April 12, 2024",
    excerpt: "Best ROI Home Improvements for Your Home",
  },
  {
    id: "ultimate-guide-to-selling-your-house",
    image: "/images/hero-image-2.jpg",
    title: "Ultimate Guide to Selling Your House",
    author: "Cindy Bond",
    date: "April 12, 2024",
    excerpt: "Best ROI Home Improvements for Your Home",
  },
];
